Refactor google login
eastor112/vocationalTestApp pull request #36
Opened 2022-04-01 04:58 UTC by eastor112

### Descripción
Refactor google login with react-google-login
Remove firebase from project dependencies

### Feeling
[//]: <> (Como te sientes con este PR? la solucion que entregas como te hace sentir?)
- [ ] 🤙 Solucion rapida
- [x] 👌 Terminado y listo
- [ ] 🤞 Espero que esto funcione, por favor revisar cuidadosamente

### Tickets
[//]: <> (El numero del ticket asociado a este PR)
G1MAV-17

### Scope

- [ ] 🐞 Bugfix (non-breaking changes que resuelve un problema
- [x] 💚 Mejora (non-breaking change que agrega/modifica funcionalidad a una característica existente)
- [ ] ⚡️ Nueva característica/feature (non-breaking change que agrega una nueva característica)
- [ ] ⚠️ Breaking change (cambio que no es compatible con versiones anteriores y/o cambia la funcionalidad actual)

2022-04-06 04:10 UTC, mhbuiles requested changes

2022-04-06 04:10 UTC, mhbuiles commented on src/components/organisms/socialMediaLoginSignup/SocialMediaLoginOrSignup.jsx
> +  console.log(error);
No console.log

2022-04-06 04:10 UTC, mhbuiles commented on src/components/organisms/socialMediaLoginSignup/SocialMediaLoginOrSignup.jsx
> +    console.log(e);
No console.log

2022-04-06 15:13 UTC, eastor112 commented on src/components/organisms/socialMediaLoginSignup/SocialMediaLoginOrSignup.jsx
> +  console.log(error);
Listo Mateo, ya lo quite

2022-04-06 15:13 UTC, eastor112 commented on src/components/organisms/socialMediaLoginSignup/SocialMediaLoginOrSignup.jsx
> +    console.log(e);
Listo Mateo, ya lo quite

2022-04-07 02:13 UTC, mhbuiles approved these changes

2022-04-07 02:50 UTC, merged